servo_controller:
  joints:
    angle_sgn: 1
    angle_scale: 0.001534
    zero_point_offset: 2047

    controller1:
      id: 0
      name: arm_joint1_joint1
      simulation:
        pid: {p: 10.0, i: 0.5, d: 0.2, i_clamp_max: 2.0, i_clamp_min: -2.0}
        init_value: 0
        type: effort_controllers/JointPositionController

    controller2:
      id: 1
      name: arm_joint2_joint1
      simulation:
        pid: {p: 10.0, i: 0.5, d: 0.2, i_clamp_max: 2.0, i_clamp_min: -2.0}
        init_value: 0
        type: effort_controllers/JointPositionController

    controller3:
      id: 2
      name: arm_joint3_joint1
      simulation:
        pid: {p: 10.0, i: 0.5, d: 0.2, i_clamp_max: 2.0, i_clamp_min: -2.0}
        init_value: 0
        type: effort_controllers/JointPositionController

    controller4:
      id: 3
      name: arm_joint4_joint1
      simulation:
        pid: {p: 10.0, i: 0.5, d: 0.2, i_clamp_max: 2.0, i_clamp_min: -2.0}
        init_value: 0
        type: effort_controllers/JointPositionController

    controller5:
      id: 4
      name: arm_joint5_joint1
      simulation:
        pid: {p: 5.0, i: 0.1, d: 0.1, i_clamp_max: 2.0, i_clamp_min: -2.0}
        init_value: 0
        type: effort_controllers/JointPositionController

