<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>aerial_robot_simulation</name>
  <version>1.3.6</version>
  <description>The aerial_robot_simulation package</description>

  <maintainer email="chou@jsk.imi.i.u-tokyo.ac.jp">chou</maintainer>

  <license>BSD</license>

  <author>Moju Zhao</author>

  <buildtool_depend condition="$ROS_VERSION == 1">catkin</buildtool_depend>
  <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake</buildtool_depend>

  <depend>mujoco_ros</depend>
  <depend>mujoco_ros_control</depend>
  <depend>pluginlib</depend>

  <depend condition="$ROS_VERSION == 1">aerial_robot_base</depend>
  <depend condition="$ROS_VERSION == 1">aerial_robot_estimation</depend>
  <depend condition="$ROS_VERSION == 1">aerial_robot_msgs</depend>
  <depend condition="$ROS_VERSION == 1">aerial_robot_model</depend>
  <depend condition="$ROS_VERSION == 1">controller_interface</depend>
  <depend condition="$ROS_VERSION == 1">gazebo_ros_control</depend>
  <depend condition="$ROS_VERSION == 1">kdl_parser</depend>
  <depend condition="$ROS_VERSION == 1">mujoco_ros_sensors</depend>
  <depend condition="$ROS_VERSION == 1">roscpp</depend>
  <depend condition="$ROS_VERSION == 1">spinal</depend>
  <depend condition="$ROS_VERSION == 1">tf</depend>

  <build_depend condition="$ROS_VERSION == 1">liburdfdom-headers-dev</build_depend>
  <exec_depend condition="$ROS_VERSION == 1">controller_manager</exec_depend>
  <exec_depend condition="$ROS_VERSION == 1">gazebo_ros</exec_depend>
  <exec_depend condition="$ROS_VERSION == 1">hector_gazebo_plugins</exec_depend>
  <exec_depend condition="$ROS_VERSION == 1">ros_controllers</exec_depend>

  <depend condition="$ROS_VERSION == 2">hardware_interface</depend>
  <depend condition="$ROS_VERSION == 2">lifecycle_msgs</depend>
  <depend condition="$ROS_VERSION == 2">rclcpp</depend>
  <depend condition="$ROS_VERSION == 2">rclcpp_lifecycle</depend>

  <export>
    <gazebo_ros_control condition="$ROS_VERSION == 1" plugin="${prefix}/aerial_robot_hw_sim_plugins.xml"/>
    <controller_interface condition="$ROS_VERSION == 1" plugin="${prefix}/flight_controllers_plugins.xml"/>
    <mujoco_ros condition="$ROS_VERSION == 1" plugin="${prefix}/mujoco_visualization_plugin.xml"/>
    <mujoco_ros_control condition="$ROS_VERSION == 1" plugin="${prefix}/mujoco_robot_hw_sim_plugin.xml"/>
    <controller_interface condition="$ROS_VERSION == 1" plugin="${prefix}/rotor_controllers_plugin.xml"/>
    <build_type condition="$ROS_VERSION == 1">catkin</build_type>
    <build_type condition="$ROS_VERSION == 2">ament_cmake</build_type>
  </export>

</package>
