# ROS2 build of hydrus.
#
# Covers the two pluginlib libraries - the robot models and the LQI controllers
# - and the config, description and MuJoCo model. Deliberately narrower than the
# ROS1 build: the numerical jacobian test library and its gtest binary are left
# out, as aerial_robot_model's equivalent already is.
#
# The MuJoCo model is not regenerated here. mujoco_model_convert lives in
# mujoco_ros_utils, which is ROS1-only and writes into the source tree; the ROS2
# build consumes what the ROS1 build produced.

add_compile_options(-std=c++17)
add_definitions(-DAERIAL_ROBOT_ROS_VERSION=2)

find_package(ament_cmake REQUIRED)

find_package(aerial_robot_control REQUIRED)
find_package(aerial_robot_estimation REQUIRED)
find_package(aerial_robot_model REQUIRED)
find_package(aerial_robot_msgs REQUIRED)
find_package(aerial_robot_ros_compat REQUIRED)
find_package(pluginlib REQUIRED)
find_package(rclcpp REQUIRED)
find_package(spinal REQUIRED)
find_package(std_srvs REQUIRED)
find_package(tf2 REQUIRED)

find_package(Eigen3 REQUIRED)

set(HYDRUS_DEPS
  aerial_robot_control
  aerial_robot_estimation
  aerial_robot_model
  aerial_robot_msgs
  aerial_robot_ros_compat
  pluginlib
  rclcpp
  spinal
  std_srvs
  tf2
)

# Eigen requires optimization to get good performance
# http://eigen.tuxfamily.org/index.php?title=FAQ#Optimization
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE RelWithDebInfo)
endif()
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O3 -g -DNDEBUG")

include_directories(
  include
  # aerial_robot_control and aerial_robot_estimation export their targets, but
  # their headers are not always propagated onto consumers' compile lines.
  ${aerial_robot_control_INCLUDE_DIRS}
  ${aerial_robot_estimation_INCLUDE_DIRS}
  ${EIGEN3_INCLUDE_DIRS}
)

add_library(hydrus_robot_model SHARED
  src/hydrus_robot_model.cpp
  src/hydrus_tilted_robot_model.cpp)
ament_target_dependencies(hydrus_robot_model ${HYDRUS_DEPS})
target_link_libraries(hydrus_robot_model aerial_robot_model::aerial_robot_model_lib)
# On the target, not just the directory: ament_target_dependencies picks up a
# dependency's include directories from its exported *targets*, so a package
# that only calls include_directories() exports headers a consumer cannot find.
# dragon and hydrus_xi include <hydrus/...>.
target_include_directories(hydrus_robot_model PUBLIC
  "$<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>"
  "$<INSTALL_INTERFACE:include>")

add_library(hydrus_controller_pluginlib SHARED
  src/hydrus_lqi_controller.cpp
  src/hydrus_tilted_lqi_controller.cpp)
ament_target_dependencies(hydrus_controller_pluginlib ${HYDRUS_DEPS})
target_link_libraries(hydrus_controller_pluginlib
  hydrus_robot_model
  aerial_robot_control::flight_control_pluginlib)
target_include_directories(hydrus_controller_pluginlib PUBLIC
  "$<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>"
  "$<INSTALL_INTERFACE:include>")

pluginlib_export_plugin_description_file(aerial_robot_model plugins/robot_model_plugins.ros2.xml)
pluginlib_export_plugin_description_file(aerial_robot_control plugins/flight_control_plugins.ros2.xml)

install(DIRECTORY include/${PROJECT_NAME}/
  DESTINATION include/${PROJECT_NAME})

install(TARGETS hydrus_robot_model hydrus_controller_pluginlib
  EXPORT export_${PROJECT_NAME}
  ARCHIVE DESTINATION lib
  LIBRARY DESTINATION lib
  RUNTIME DESTINATION bin)

install(DIRECTORY config plugins robots urdf
  DESTINATION share/${PROJECT_NAME}
  USE_SOURCE_PERMISSIONS)

# Only the python launch file; the .launch XML beside it is the ROS1 one and
# starts gazebo, the spinal bridge and servo_bridge.
install(FILES launch/bringup.launch.py
  DESTINATION share/${PROJECT_NAME}/launch)


# The generated mujoco/<type>/<onboards_model>/robot.xml pulls in the shared
# world through a path relative to the *source* tree, and that relationship does
# not survive installation. Resolve it here, where the source layout is still
# real, and install a self-contained model directory per variant: robot.xml with
# a bare <include file="world.xml"/>, and the world beside it.
file(GLOB_RECURSE MUJOCO_ROBOT_SOURCES
  RELATIVE ${PROJECT_SOURCE_DIR}/mujoco
  ${PROJECT_SOURCE_DIR}/mujoco/*/*/robot.xml)
# Missing is a warning, not an error. The models are gitignored build products
# of mujoco_ros_utils' generator, which under ROS2 runs *after* this build -
# `$(find <pkg>)` in a robot's xacro needs the package installed, so it cannot
# run during the package's own build. See docs/ros2_migration.md. Everything
# else here still builds; only the simulation has nothing to load.
if(NOT MUJOCO_ROBOT_SOURCES)
  message(WARNING
    "No mujoco/*/*/robot.xml found, so no MuJoCo model will be installed. "
    "They are generated by the ROS1 build (mujoco_model_convert in "
    "aerial_robot_3rdparty's mujoco_ros_utils); run catkin build once if you "
    "want to simulate this robot.")
endif()

foreach(_rel ${MUJOCO_ROBOT_SOURCES})
  set(_src ${PROJECT_SOURCE_DIR}/mujoco/${_rel})
  get_filename_component(_dir ${_rel} DIRECTORY)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_src})

  file(READ ${_src} _xml)
  string(REGEX MATCH "<include file=\"([^\"]*)\"" _matched "${_xml}")
  if(NOT CMAKE_MATCH_1)
    message(FATAL_ERROR "No <include file=...> found in ${_src}")
  endif()
  get_filename_component(_world "${PROJECT_SOURCE_DIR}/mujoco/${_dir}/${CMAKE_MATCH_1}" ABSOLUTE)
  if(NOT EXISTS ${_world})
    message(FATAL_ERROR "MuJoCo world ${_world} does not exist")
  endif()

  string(REGEX REPLACE "<include file=\"[^\"]*\"" "<include file=\"world.xml\"" _xml "${_xml}")
  file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/mujoco/${_rel} "${_xml}")
  install(FILES ${CMAKE_CURRENT_BINARY_DIR}/mujoco/${_rel} ${_world}
    DESTINATION share/${PROJECT_NAME}/mujoco/${_dir})
endforeach()

# The meshes the models reference. mujoco_model_convert points every generated
# model at the meshes beside it, so they install into each variant's directory.
foreach(_rel ${MUJOCO_ROBOT_SOURCES})
  get_filename_component(_dir ${_rel} DIRECTORY)
  install(DIRECTORY ${PROJECT_SOURCE_DIR}/mujoco/${_dir}/
    DESTINATION share/${PROJECT_NAME}/mujoco/${_dir}
    FILES_MATCHING PATTERN "*.stl" PATTERN "*.STL")
endforeach()

ament_export_include_directories(include)
ament_export_targets(export_${PROJECT_NAME} HAS_LIBRARY_TARGET)
ament_export_dependencies(${HYDRUS_DEPS})

ament_package()
