# ROS2 build of mini_quadrotor.
#
# The package has no code; it installs the robot's description, its config and
# its launch files. Deliberately narrower than the ROS1 build (see Ros1.cmake):
#
#   - The MuJoCo model is not regenerated. mujoco_model_convert lives in
#     mujoco_ros_utils, which is ROS1-only, and it writes into the source tree.
#     The ROS2 build consumes the mujoco/ directory the ROS1 build produced.
#   - bin/ and test/ are ROS1-only: rosbag_record.sh drives `rosbag record` and
#     the hovering test is a rostest.

find_package(ament_cmake REQUIRED)

install(DIRECTORY config urdf
  DESTINATION share/${PROJECT_NAME}
  USE_SOURCE_PERMISSIONS)

# Only the python launch files. The .launch XML alongside them is the ROS1 one
# and refers to gazebo and the spinal serial bridge, neither of which has a
# ROS2 build here; installing it would just invite `ros2 launch` to try.
install(FILES launch/bringup.launch.py
  DESTINATION share/${PROJECT_NAME}/launch)

# The generated mujoco/robot.xml pulls in the shared world through a path
# relative to the *source* tree ("../../../../aerial_robot_3rdparty/..."), and
# that relationship does not survive installation. Resolve it here, where the
# source layout is still real, and install a self-contained pair: robot.xml
# with a bare <include file="world.xml"/>, and the world beside it.
set(MUJOCO_ROBOT_SOURCE ${PROJECT_SOURCE_DIR}/mujoco/robot.xml)
if(NOT EXISTS ${MUJOCO_ROBOT_SOURCE})
  message(FATAL_ERROR
    "${MUJOCO_ROBOT_SOURCE} is missing. It is generated by the ROS1 build "
    "(mujoco_model_convert); run catkin build once before building for ROS2.")
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${MUJOCO_ROBOT_SOURCE})

file(READ ${MUJOCO_ROBOT_SOURCE} MUJOCO_ROBOT_XML)
string(REGEX MATCH "<include file=\"([^\"]*)\"" _matched "${MUJOCO_ROBOT_XML}")
if(NOT CMAKE_MATCH_1)
  message(FATAL_ERROR "No <include file=...> found in ${MUJOCO_ROBOT_SOURCE}")
endif()
get_filename_component(MUJOCO_WORLD_SOURCE
  "${PROJECT_SOURCE_DIR}/mujoco/${CMAKE_MATCH_1}" ABSOLUTE)
if(NOT EXISTS ${MUJOCO_WORLD_SOURCE})
  message(FATAL_ERROR "MuJoCo world ${MUJOCO_WORLD_SOURCE} does not exist")
endif()

string(REGEX REPLACE "<include file=\"[^\"]*\"" "<include file=\"world.xml\""
  MUJOCO_ROBOT_XML "${MUJOCO_ROBOT_XML}")
file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/mujoco/robot.xml "${MUJOCO_ROBOT_XML}")

install(FILES
  ${CMAKE_CURRENT_BINARY_DIR}/mujoco/robot.xml
  ${MUJOCO_WORLD_SOURCE}
  DESTINATION share/${PROJECT_NAME}/mujoco)

# The meshes the model references sit next to it in the source tree.
install(DIRECTORY ${PROJECT_SOURCE_DIR}/mujoco/
  DESTINATION share/${PROJECT_NAME}/mujoco
  FILES_MATCHING PATTERN "*.stl")

ament_package()
